### PR TITLE
Community bot slash commands feature

### LINKED ISSUE #21: Add slash command integration
Might require different types of inputs that should be released by the time that Discord itself requires slash commands to be used for bots

### PR DESCRIPTION
**Pull request by luckspt**
This PR should fix #21 when merged

### CODE REVIEW

**Comment by luckspt** [comment]
Right now I am having some difficulty with the typings, it does force me to use `requiresApikey` and `fetchFilters` on base commands, which should be handled on each subcommand

**Comment by oof2win2** [comment]
I think that `requiresApikey` and `fetchFilters` would need to be used if *any* of the subcommands have those set to true, as you can't handle them mid-way in the execution of subcommands - at least so far.

**Comment by luckspt** [comment]
I made two major changes (I hope I didn't forget any others)
- set api key will use a modal to not show any api keys in the guild
- `getConfirmation` will use button interaction instead of reactions. It now takes a message or command interaction and requires the target user to be specified

There's also a logic change on `/config set contact` to not allow for bots

**Comment by luckspt** [comment]
I have not ported the `help` command because the discord slash command selector should be enough.
Is this something you'd like ported?

**Comment by oof2win2** [comment]
Happy with the changes. Ready to merge the PR when you are.

**Comment by luckspt** [comment]
At the moment I am making a change to embed pagination so it accepts a message or interaction just like the `getConfirmation`
I also haven't revised the usage of both because they now support interactions.

**Comment by oof2win2** [comment]
Possibly make it support interactions only? I don't think we will be using messages anymore since it doesn't make sense to do so.

**Comment by luckspt** [comment]
We may use it on `followUp`s?
I also noticed that to add a category they first need to be cached, but that won't happen until someone lists all the categories

**Comment by luckspt** [comment]
I don't know how to fix the branch conflict on `apps/community-bot/src/commands/communities/removecommunity.ts`. It has a button for those who have write access, so I guess that's up to you,

**Review by oof2win2 — APPROVED** [review]

**Comment by oof2win2** [comment]
Sorry, forgot about the conflicts. Thanks a lot for the PR, it was a lot of stuff!

**Pull request merged**
